---
- name: EC2 Test Example
  hosts: localhost
  connection: local
  gather_facts: False
  environment:
    AWS_ACCESS_KEY_ID: "AKIA6CXQOFMVMCIQCW7T"
    AWS_SECRET_ACCESS_KEY: "+aXBlUrYmr1jUjntOZmaI2nh5blqD0E3GfcmF40i"
    AWS_DEFAULT_REGION: "us-east-2"
  vars:
    st_type: present
  tasks:
  - name: start specific number of multiple instances
    amazon.aws.ec2_instance:
      instance_type: t2.micro
      image_id: ami-024e6efaf93d85776
      count: 1
      region: us-east-2
      network:
        assign_public_ip: true
        security_group: default
        vpc_subnet_id: subnet-09ff655fb2c442ab8
      state: present
      tags:
        env: devo
