---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False

  environment:
    AWS_ACCESS_KEY_ID: "AKIA6CXQOFMVMCIQCW7T"
    AWS_SECRET_ACCESS_KEY: "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"
    AWS_DEFAULT_REGION: "us-east-2"
  vars:
    region: "us-east-2"  
    instance_type: "t2.micro"  
    image_id: "ami-024e6efaf93d85776"  
    security_group: "default"
    key_pair: "raviohio"
    subnet_id: "subnet-09ff655fb2c442ab8" 
  tasks:
    - name: Create EC2 Instance
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_pair }}"
        instance_type: "{{ instance_type }}"
        image: "{{ image_id }}"
        wait: yes
        group: "{{ security_group }}"
        vpc_subnet_id: "{{ subnet_id }}"
        assign_public_ip: yes
        count: 1
      register: ec2_instance

    - name: Print EC2 Instance Details
      debug:
        var: ec2_instance
