---
- debug:
    msg: "{{ item }}"
- name: Pull default Docker image
  community.docker.docker_image:
    name: "{{ item }}"
    source: pull

- name: Create default containers
  community.docker.docker_container:
    name: "{{ item }}"
    image: "{{ item }}"
    command: "{{ default_container_command }}"
    state: "{{ op_type }}"